language: php

php:
  - 7.3
  - 7.4
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit